// Generated by firmware/sim/tools/temp_scale.py. Do not edit by hand; a stop's
// numbers live in that script's STOPS, not here. Regenerate with:
//     python3 firmware/sim/tools/temp_scale.py
//
// The weather strip's bar colour: an absolute Celsius-to-colour scale, so a given whole-degree
// reading is always the same colour, on any day, rather than the brightest or dimmest hue in
// that day's own six-hour range. Linearly interpolated in OKLCH L, C and H between the
// design's eight stops, five degrees apart; NIGHT keeps each degree's L and H and halves its
// C, the rule firmware/hb_tokens.h's own NIGHT palette uses.
#pragma once

#include <cstdint>

namespace hb {

// Index 0 is -5 C, index 35 is 30 C: table[celsius - (-5)], celsius
// clamped to [-5, 30] first.
inline constexpr uint32_t TEMP_SCALE_DAY[36] = {
    0x7FAFE2,  // -5 C
    0x7AB0E2,  // -4 C
    0x76B2E2,  // -3 C
    0x71B3E2,  // -2 C
    0x6CB4E2,  // -1 C
    0x67B5E1,  // 0 C
    0x63B7DF,  // 1 C
    0x60B9DD,  // 2 C
    0x5DBBDB,  // 3 C
    0x5ABCD8,  // 4 C
    0x58BED5,  // 5 C
    0x56C0D1,  // 6 C
    0x55C1CD,  // 7 C
    0x55C3C9,  // 8 C
    0x56C4C4,  // 9 C
    0x59C5BF,  // 10 C
    0x5CC7B6,  // 11 C
    0x62C8AD,  // 12 C
    0x6AC9A3,  // 13 C
    0x74C999,  // 14 C
    0x7FC88F,  // 15 C
    0x91C882,  // 16 C
    0xA3C675,  // 17 C
    0xB5C46A,  // 18 C
    0xC6C161,  // 19 C
    0xD6BD5C,  // 20 C
    0xDCB657,  // 21 C
    0xE1B053,  // 22 C
    0xE6A952,  // 23 C
    0xEAA352,  // 24 C
    0xED9C55,  // 25 C
    0xED9557,  // 26 C
    0xED8E59,  // 27 C
    0xEC875D,  // 28 C
    0xEA8161,  // 29 C
    0xE87A65,  // 30 C
};

inline constexpr uint32_t TEMP_SCALE_NIGHT[36] = {
    0x96AEC7,  // -5 C
    0x94AEC7,  // -4 C
    0x92AFC7,  // -3 C
    0x90AFC7,  // -2 C
    0x8FB0C7,  // -1 C
    0x8DB1C6,  // 0 C
    0x8CB2C6,  // 1 C
    0x8BB3C5,  // 2 C
    0x8BB4C4,  // 3 C
    0x8AB5C3,  // 4 C
    0x8AB7C2,  // 5 C
    0x8AB8C0,  // 6 C
    0x8AB9BE,  // 7 C
    0x8BBABC,  // 8 C
    0x8CBBBA,  // 9 C
    0x8DBCB8,  // 10 C
    0x8EBDB4,  // 11 C
    0x90BEB0,  // 12 C
    0x94BEAB,  // 13 C
    0x97BFA7,  // 14 C
    0x9CBFA2,  // 15 C
    0xA4BF9D,  // 16 C
    0xADBF99,  // 17 C
    0xB7BF95,  // 18 C
    0xC0BF93,  // 19 C
    0xCABE92,  // 20 C
    0xCCBA8F,  // 21 C
    0xCDB58C,  // 22 C
    0xCFB18A,  // 23 C
    0xD0AC88,  // 24 C
    0xD1A888,  // 25 C
    0xCFA386,  // 26 C
    0xCD9E85,  // 27 C
    0xCB9884,  // 28 C
    0xC99483,  // 29 C
    0xC68F83,  // 30 C
};

}  // namespace hb
