#!/usr/bin/env python3
"""temp_scale.py

What this is for
-----------------
The weather face's hourly bars used to vary the T_WEATHER hue's brightness with each day's own
temperature range: the warmest of the six slots got the full hue, the coldest about a third of
it. That meant a given temperature was a different shade on a cold day than on a hot one. This
script generates firmware/hb_temp_scale.h, an absolute Celsius-to-colour table: -5 C is always the
same colour, on any day, at any time of year.

The scale is eight stops in OKLCH, five degrees apart, from the design:

    -5 C: L 0.74, C 0.09, H 250        15 C: L 0.77, C 0.11, H 150
     0 C: L 0.74, C 0.10, H 235        20 C: L 0.80, C 0.12, H 95
     5 C: L 0.75, C 0.10, H 215        25 C: L 0.76, C 0.13, H 60
    10 C: L 0.76, C 0.10, H 190        30 C: L 0.70, C 0.14, H 32

Every whole degree from -5 to 30 is linearly interpolated between the two stops either side of it,
in L, C and H independently (the hue is monotonically decreasing across the stops, so there is no
360 degrees wrap to reason about). NIGHT keeps each degree's L and H and halves its C, the same
rule firmware/hb_tokens.h's own NIGHT palette uses (see night_palette.py) -- applied here to the
continuous OKLCH value at each degree, not to the DAY table's already-rounded sRGB, so the two
tables do not compound each other's quantising.

This script reuses night_palette.py's OKLab matrices and its sRGB <-> OKLCH conversion outright
(same file, imported, not copied), and gamut-clips an out-of-range result the same way that script
does: clamp each sRGB channel to [0, 1] before rounding to a byte. A stop or an interpolated point
that lands outside sRGB is a modelling problem, so this prints a warning rather than failing.

How to run
----------
    python3 firmware/sim/tools/temp_scale.py

This writes firmware/hb_temp_scale.h. It is a generated file: never edit it by hand, and if a
stop's numbers above ever change, edit STOPS below and run this again. Standard library only.
"""

import math
import sys
from pathlib import Path

import night_palette as base

# -------------------------------------------------------------------- the scale
# (Celsius, L, C, H), five degrees apart. STOPS must stay sorted by temperature; H must stay
# monotonic (decreasing, here) across the run so a linear interpolation of it never needs to
# reason about which way round the hue wheel to go.
STOPS = [
    (-5, 0.74, 0.09, 250),
    (0, 0.74, 0.10, 235),
    (5, 0.75, 0.10, 215),
    (10, 0.76, 0.10, 190),
    (15, 0.77, 0.11, 150),
    (20, 0.80, 0.12, 95),
    (25, 0.76, 0.13, 60),
    (30, 0.70, 0.14, 32),
]

MIN_C = STOPS[0][0]
MAX_C = STOPS[-1][0]


def oklch_at(celsius):
    """L, C, H at a whole-degree Celsius value, clamped to the stops' own range and linearly
    interpolated between the two stops either side of it otherwise."""
    if celsius <= MIN_C:
        _, l, c, h = STOPS[0]
        return l, c, h
    if celsius >= MAX_C:
        _, l, c, h = STOPS[-1]
        return l, c, h
    for (t0, l0, c0, h0), (t1, l1, c1, h1) in zip(STOPS, STOPS[1:]):
        if t0 <= celsius <= t1:
            f = (celsius - t0) / (t1 - t0)
            return l0 + (l1 - l0) * f, c0 + (c1 - c0) * f, h0 + (h1 - h0) * f
    raise AssertionError(f"{celsius} C is not covered by STOPS")


def oklch_to_srgb_hex_checked(l, c, h, label):
    """base.oklch_to_srgb_hex, plus a look at the un-clamped sRGB so an out-of-gamut stop prints a
    warning instead of silently rounding to the nearest in-gamut colour."""
    hr = math.radians(h)
    a = c * math.cos(hr)
    b_ = c * math.sin(hr)
    lms_prime = base.mat_vec(base.M2_INV, [l, a, b_])
    lms = [x ** 3 for x in lms_prime]
    rl, gl, bl = base.mat_vec(base.M1_INV, lms)
    r, g, bch = base.linear_to_srgb(rl), base.linear_to_srgb(gl), base.linear_to_srgb(bl)
    if not (0.0 <= r <= 1.0 and 0.0 <= g <= 1.0 and 0.0 <= bch <= 1.0):
        print(
            f"warning: {label} (L {l:.4f} C {c:.4f} H {h:.2f}) is outside sRGB "
            f"(r {r:.3f} g {g:.3f} b {bch:.3f}); gamut-clipped by clamping each channel",
            file=sys.stderr,
        )
    return base.rgb01_to_hex(r, g, bch)


def build_table(night):
    rows = []
    for celsius in range(MIN_C, MAX_C + 1):
        l, c, h = oklch_at(celsius)
        if night:
            c = c / 2.0
        label = f"{celsius} C" + (" (night)" if night else "")
        rows.append((celsius, oklch_to_srgb_hex_checked(l, c, h, label)))
    return rows


def render(path):
    day = build_table(night=False)
    night = build_table(night=True)
    n = len(day)

    lines = []
    lines.append("// Generated by firmware/sim/tools/temp_scale.py. Do not edit by hand; a stop's")
    lines.append("// numbers live in that script's STOPS, not here. Regenerate with:")
    lines.append("//     python3 firmware/sim/tools/temp_scale.py")
    lines.append("//")
    lines.append("// The weather strip's bar colour: an absolute Celsius-to-colour scale, so a given whole-degree")
    lines.append("// reading is always the same colour, on any day, rather than the brightest or dimmest hue in")
    lines.append("// that day's own six-hour range. Linearly interpolated in OKLCH L, C and H between the")
    lines.append("// design's eight stops, five degrees apart; NIGHT keeps each degree's L and H and halves its")
    lines.append("// C, the rule firmware/hb_tokens.h's own NIGHT palette uses.")
    lines.append("#pragma once")
    lines.append("")
    lines.append("#include <cstdint>")
    lines.append("")
    lines.append("namespace hb {")
    lines.append("")
    lines.append(f"// Index 0 is {MIN_C} C, index {n - 1} is {MAX_C} C: table[celsius - ({MIN_C})], celsius")
    lines.append(f"// clamped to [{MIN_C}, {MAX_C}] first.")
    lines.append(f"inline constexpr uint32_t TEMP_SCALE_DAY[{n}] = {{")
    for celsius, hexval in day:
        lines.append(f"    0x{hexval:06X},  // {celsius} C")
    lines.append("};")
    lines.append("")
    lines.append(f"inline constexpr uint32_t TEMP_SCALE_NIGHT[{n}] = {{")
    for celsius, hexval in night:
        lines.append(f"    0x{hexval:06X},  // {celsius} C")
    lines.append("};")
    lines.append("")
    lines.append("}  // namespace hb")
    lines.append("")

    text = "\n".join(lines)
    path.write_text(text)
    return text


def main():
    out = Path(__file__).resolve().parent.parent.parent / "hb_temp_scale.h"
    render(out)
    print(f"wrote {out}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
